In [2]:
import numpy as np
import pandas as pd

df=pd.read_csv('Course_info.csv')
df.shape

(209734, 20)

In [7]:
# df.head()#shows 5 values from top .csv file
df.tail()#shows 5 values from bottom .csv file

,id,title,is_paid,price,headline,num_subscribers,avg_rating,num_reviews,num_comments,num_lectures,content_length_min,published_time,last_update_date,category,subcategory,topic,language,course_url,instructor_name,instructor_url
209729,4913954.0,Let's Speak Urdu - The Urdu Grammar,True,19.99,Urdu - Become fluent in this beautiful South A...,3.0,0.0,0.0,0.0,5.0,54.0,2022-10-05T11:31:36Z,2022-10-06,Teaching & Academics,Language Learning,Urdu Language,English,/course/lets-speak-urdu-the-grammar/,Jawaid Hameed,/user/jawaid-hameed/
209730,4914146.0,CompTIA Linux+ (XKO-004/005 # 2 Practice Exam ...,True,49.99,Practice Latest exam questions with detailed e...,0.0,0.0,0.0,0.0,0.0,0.0,2022-10-05T12:29:23Z,2022-10-05,IT & Software,IT Certifications,CompTIA Linux+,English,/course/comptia-linux-xko-004005-2-practice-ex...,Jean-François d'Halluin,/user/badre-lini/
209731,4914002.0,CISSP 4 full exams #1 : All CISSP domains - 12...,True,49.99,Practice Latest exam questions with detailed e...,0.0,0.0,0.0,0.0,0.0,0.0,2022-10-05T11:04:05Z,2022-10-05,IT & Software,IT Certifications,CISSP - Certified Information Systems Security...,English,/course/cissp-4-full-exams-1-all-cissp-domains...,Jean-François d'Halluin,/user/badre-lini/
209732,4913934.0,JD Edwards EnterpriseOne Fixed Assets Accounti...,True,119.99,Full-length course (Part-3 of 3) on JD Edwards...,0.0,0.0,0.0,0.0,9.0,82.0,2022-10-05T10:30:19Z,2022-10-05,Finance & Accounting,Other Finance & Accounting,Financial Accounting,English,/course/jde-fixed-assets-accounting-part-3/,Niranjan Bhatia,/user/systemic-software-solutions/
209733,4914054.0,CISSP 4 full exams #2 : All CISSP domains - 12...,True,49.99,Practice Latest exam questions with detailed e...,0.0,0.0,0.0,0.0,0.0,0.0,2022-10-05T11:36:34Z,2022-10-05,IT & Software,IT Certifications,CISSP - Certified Information Systems Security...,English,/course/cissp-4-full-exams-2-all-cissp-domains...,Jean-François d'Halluin,/user/badre-lini/

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209734 entries, 0 to 209733
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  209734 non-null  float64
 1   title               209734 non-null  object
 2   is_paid             209734 non-null  bool
 3   price               209734 non-null  float64
 4   headline            209703 non-null  object
 5   num_subscribers     209734 non-null  float64
 6   avg_rating          209734 non-null  float64
 7   num_reviews         209734 non-null  float64
 8   num_comments        209734 non-null  float64
 9   num_lectures        209734 non-null  float64
 10  content_length_min  209734 non-null  float64
 11  published_time      209734 non-null  object
 12  last_update_date    209597 non-null  object
 13  category            209734 non-null  object
 14  subcategory         209734 non-null  object
 15  topic               208776 non-null  object
 16  language            209734 non-null  object
 17  course_url          209734 non-null  object
 18  instructor_name     209729 non-null  object
 19  instructor_url      209307 non-null  object
dtypes: bool(1), float64(8), object(11)
memory usage: 30.6+ MB

In [9]:
df.isnull().sum()

id                      0
title                   0
is_paid                 0
price                   0
headline               31
num_subscribers         0
avg_rating              0
num_reviews             0
num_comments            0
num_lectures            0
content_length_min      0
published_time          0
last_update_date      137
category                0
subcategory             0
topic                 958
language                0
course_url              0
instructor_name         5
instructor_url        427
dtype: int64

In [11]:
df["avg_rating"]=df["avg_rating"].astype("int")
df["avg_rating"].dtypes

dtype('int32')

In [16]:
df.columns

Index(['id', 'title', 'is_paid', 'price', 'headline', 'num_subscribers',
       'avg_rating', 'num_reviews', 'num_comments', 'num_lectures',
       'content_length_min', 'published_time', 'last_update_date', 'category',
       'subcategory', 'topic', 'language', 'course_url', 'instructor_name',
       'instructor_url'],
      dtype='object')

In [1]:
for i in range(len(df.columns)):
    if df.dtypes[i]=="dtype('int32')":
        df[df.columns[i]]=df[df.columns[i]].astype("float")
        df[df.columns[i]].dtypes

NameError: name 'df' is not defined

In [102]:
for i in range(len(df.columns)):
    if df.dtypes.iloc[i]=="float64":
        df[df.columns[i]]=df[df.columns[i]].astype("int")
    print(df[df.columns[i]].dtypes)

int32
object
bool
int32
object
int32
int32
int32
int32
int32
int32
object
object
object
object
object
object
object
object
object

In [108]:
df.drop(["avg_rating"],axis=1,inplace=True)
df

,id,title,is_paid,price,headline,num_subscribers,num_reviews,num_comments,num_lectures,content_length_min,published_time,last_update_date,category,subcategory,topic,language,course_url,instructor_name,instructor_url
0,4715,Online Vegan Vegetarian Cooking School,True,24,Learn to cook delicious vegan recipes. Filmed ...,2231,134,42,37,1268,2010-08-05T22:06:13Z,2020-11-06,Lifestyle,Food & Beverage,Vegan Cooking,English,/course/vegan-vegetarian-cooking-school/,Angela Poch,/user/angelapoch/
1,1769,The Lean Startup Talk at Stanford E-Corner,False,0,Debunking Myths of Entrepreneurship A startup ...,26474,709,112,9,88,2010-01-12T18:09:46Z,NaN,Business,Entrepreneurship,Lean Startup,English,/course/the-lean-startup-debunking-myths-of-en...,Eric Ries,/user/ericries/
2,5664,"How To Become a Vegan, Vegetarian, or Flexitarian",True,19,Get the tools you need for a lifestyle change ...,1713,41,13,14,82,2010-10-13T18:07:17Z,2019-10-09,Lifestyle,Other Lifestyle,Vegan Cooking,English,/course/see-my-personal-motivation-for-becomin...,Angela Poch,/user/angelapoch/
3,7723,How to Train a Puppy,True,199,Train your puppy the right way with Dr. Ian Du...,4988,395,88,36,1511,2011-06-20T20:08:38Z,2016-01-13,Lifestyle,Pet Care & Training,Pet Training,English,/course/complete-dunbar-collection/,Ian Dunbar,/user/ian-dunbar/
4,8157,Web Design from the Ground Up,True,159,Learn web design online: Everything you need t...,1266,38,12,38,569,2011-06-23T18:31:20Z,NaN,Design,Web Design,Web Design,English,/course/web-design-from-the-ground-up/,E Learning Lab,/user/edwin-ang-2/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209729,4913954,Let's Speak Urdu - The Urdu Grammar,True,19,Urdu - Become fluent in this beautiful South A...,3,0,0,5,54,2022-10-05T11:31:36Z,2022-10-06,Teaching & Academics,Language Learning,Urdu Language,English,/course/lets-speak-urdu-the-grammar/,Jawaid Hameed,/user/jawaid-hameed/
209730,4914146,CompTIA Linux+ (XKO-004/005 # 2 Practice Exam ...,True,49,Practice Latest exam questions with detailed e...,0,0,0,0,0,2022-10-05T12:29:23Z,2022-10-05,IT & Software,IT Certifications,CompTIA Linux+,English,/course/comptia-linux-xko-004005-2-practice-ex...,Jean-François d'Halluin,/user/badre-lini/
209731,4914002,CISSP 4 full exams #1 : All CISSP domains - 12...,True,49,Practice Latest exam questions with detailed e...,0,0,0,0,0,2022-10-05T11:04:05Z,2022-10-05,IT & Software,IT Certifications,CISSP - Certified Information Systems Security...,English,/course/cissp-4-full-exams-1-all-cissp-domains...,Jean-François d'Halluin,/user/badre-lini/
209732,4913934,JD Edwards EnterpriseOne Fixed Assets Accounti...,True,119,Full-length course (Part-3 of 3) on JD Edwards...,0,0,0,9,82,2022-10-05T10:30:19Z,2022-10-05,Finance & Accounting,Other Finance & Accounting,Financial Accounting,English,/course/jde-fixed-assets-accounting-part-3/,Niranjan Bhatia,/user/systemic-software-solutions/
209733,4914054,CISSP 4 full exams #2 : All CISSP domains - 12...,True,49,Practice Latest exam questions with detailed e...,0,0,0,0,0,2022-10-05T11:36:34Z,2022-10-05,IT & Software,IT Certifications,CISSP - Certified Information Systems Security...,English,/course/cissp-4-full-exams-2-all-cissp-domains...,Jean-François d'Halluin,/user/badre-lini/